#!/usr/bin/env bun
/**
 * Prebuild codegen — reads all Phosphor regular-weight SVGs and generates
 * a TypeScript module exporting a name → innerSvg map.
 *
 * Output: src/generated/phosphorSvgMap.ts
 * Run via: bun run scripts/codegen-phosphor-svgs.ts
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const phosphorEntry = require.resolve("@phosphor-icons/core");
const phosphorRoot = dirname(dirname(phosphorEntry));
const svgDir = join(phosphorRoot, "assets", "regular");

const INNER_SVG_REGEX = /<svg[^>]*>([\s\S]*?)<\/svg>/i;
const OUTPUT_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "../src/generated/phosphorSvgMap.ts",
);

async function generate(): Promise<void> {
  const files = (await readdir(svgDir)).filter((f) => f.endsWith(".svg")).sort();

  const entries: string[] = [];

  for (const file of files) {
    const name = file.replace(/\.svg$/, "");
    const svg = await readFile(join(svgDir, file), "utf8");
    const innerSvg = svg.match(INNER_SVG_REGEX)?.[1]?.trim();
    if (!innerSvg) {
      console.warn(`[codegen] Skipping ${file}: could not extract inner SVG`);
      continue;
    }
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(innerSvg)}`);
  }

  const output = [
    "// Auto-generated by scripts/codegen-phosphor-svgs.ts — do not edit",
    "// Run `bun run prebuild` to regenerate after upgrading @phosphor-icons/core",
    "",
    "export const PHOSPHOR_SVG_MAP: Record<string, string> = {",
    entries.join(",\n"),
    "};",
    "",
  ].join("\n");

  await writeFile(OUTPUT_PATH, output, "utf8");
  console.log(
    `[codegen] Wrote ${entries.length} Phosphor SVG entries to src/generated/phosphorSvgMap.ts`,
  );
}

generate().catch((err) => {
  console.error("[codegen] Failed:", err);
  process.exit(1);
});
