services:
  astro-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      no_cache: true
      pull: true
      args:
        ASTRO_SITE_URL: ${ASTRO_SITE_URL}
        ASTRO_CMS_API_URL: ${ASTRO_CMS_API_URL}
        ASTRO_CMS_READ_TOKEN: ${ASTRO_CMS_READ_TOKEN}
    environment:
      ASTRO_SITE_URL: ${ASTRO_SITE_URL}
      ASTRO_CMS_API_URL: ${ASTRO_CMS_API_URL}
      ASTRO_CMS_READ_TOKEN: ${ASTRO_CMS_READ_TOKEN}
      HOST: 0.0.0.0
      PORT: 4321
    ports:
      - "${WEB_PORT:-4321}:4321"
